INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('chargeurameliore', '[ATTACHE] Chargeur amélioré', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('compensateur', '[ATTACHE] Compensateur', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('viseurmk2', '[ATTACHE] Viseur Pistolet MK2', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('skinluxe', '[ATTACHE] Skin Luxe', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('viseurfusil', '[ATTACHE] Viseur de fusil', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('skinpapillion', '[ATTACHE] Skin Papillion', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('skinlove', '[ATTACHE] Skin Love PA', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('viseurmoyen', '[ATTACHE] Viseur Moyen', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('viseurgrand', '[ATTACHE] Viseur Grand', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('viseurholo', '[ATTACHE] Viseur Holographique', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('platin50', '[ATTACHE] Skin Platine Calibre 50', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('skinbois', '[ATTACHE] Skin Bois Pistolet', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('skinboisfusil', '[ATTACHE] Skin Bois Fusil', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('skincranefusil', '[ATTACHE] Skin Tête de mort Fusil', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('skinzebre', '[ATTACHE] Skin Zebre Fusil', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('skinboom', '[ATTACHE] Skin Boom Fusil', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('freinbouche', '[ATTACHE] Frein de bouche tactique', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('skinpimp', '[ATTACHE] Skin PIMP PA', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('skinbalas', '[ATTACHE] Skin Ballas PA', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('skindollar', '[ATTACHE] Skin Dollar PA', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('skindiament', '[ATTACHE] Skin Diamand PA', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('skinhate', '[ATTACHE] Skin "La Haine" PA', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('skinplayer', '[ATTACHE] Skin Joueur PA', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('skinvagos', '[ATTACHE] Skin Vagos PA', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('flashlight', '[ATTACHE] Lampe', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('Suppressor', '[ATTACHE] Suppresseur', -1, 0, 1);
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('grip', '[ATTACHE] Poignée de fusil', -1, 0, 1);